version: '3.1'
services:
    app:
        build:
            dockerfile: ./Dockerfile
        image: fast-api
        container_name: "mock-php"
#        restart: always
        ports:
            - "8090:80"
#        volumes:
#          - ./output:/code/output
#          - ./app:/code/app
#        environment:
#            - REDIS_PASSWORD=redis-password
#            - REDIS_PORT=6379
#            - REDIS_DATABASES=16